"""update enum

Revision ID: 34392033bdd6
Revises: 7078bde57e9b
Create Date: 2025-11-30 21:02:59.547778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34392033bdd6'
down_revision: Union[str, Sequence[str], None] = '7078bde57e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_login'), table_name='admins')
    op.drop_table('admins')
    op.add_column('products', sa.Column('discount_percent', sa.Integer(), nullable=True))
    op.drop_column('products', 'old_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('old_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'discount_percent')
    op.create_table('admins',
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey'))
    )
    op.create_index(op.f('ix_admins_login'), 'admins', ['login'], unique=True)
    # ### end Alembic commands ###
