"""Update settings model

Revision ID: 7078bde57e9b
Revises: e904e34799f1
Create Date: 2025-11-29 03:23:32.951445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7078bde57e9b'
down_revision: Union[str, Sequence[str], None] = 'e904e34799f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'order')
    op.add_column('settings', sa.Column('work_hours', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'work_hours')
    op.add_column('reviews', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
